### ISSUE TITLE
SVG圖檔翻轉後使用方向鍵移動會亂跳

### ISSUE THREAD

**Issue by AndyAWD** [flux3dp/beam-studio#1]
環境：Windows10 Pro  
Beam Studio 1.0.10  

1. 匯入SVG圖檔(1.0和1.1同樣結果)
2. 點擊旋轉，輸入90，Enter
3. Ctrl + C
4. Ctrl + V
5. Ctrl + A
6. 點擊水平翻轉或垂直翻轉
7. 鍵盤長按任一方向鍵，會發現圖片位置亂跳

**Comment by dkdkwizard** [comment]
Hi AndyAWD,
    最近幾次的更新已經有修改過計算 svg 圖檔的方法，目前應該已經修正這個問題。
    可以從官網下載最新的 Beam Studio 穩定版 1.1.9 或是 Beam Studio Beta版 1.2.2 來使用，如果仍會發生請再麻煩告知。
