### ISSUE TITLE
new socket: Operation not permitted

### ISSUE THREAD

**Issue by oscaracena** [flux3dp/beam-studio#13]
I've downloaded and installed the latest Beam Studio (1.4.4 beta) on Ubuntu. When I try to connect with the laser machine (using an IP address), it fails. After opening the `Debug Tool`, I see the following error:

```
Error: Operation not permitted
    at new Socket (/opt/Beam Studio/res…-socket/index.js:47)
    at Object.exports.createSocket (/opt/Beam Studio/res…socket/index.js:202)
    at Session.getSocket (/opt/Beam Studio/res…t-ping/index.js:147)
    at new Session (/opt/Beam Studio/res…t-ping/index.js:101)
    at Object.exports.createSession (/opt/Beam Studio/res…t-ping/index.js:545)
    at Connect-Machine-Ip.j…v=1600764880346:161
    at new Promise (<anonymous>)
    at ConnectMachine.pingTarget (Connect-Machine-Ip.j…v=1600764880346:157)
    at Connect-Machine-Ip.j…v=1600764880346:233
    at onClick (Connect-Machine-Ip.j…v=1600764880346:338)
```
I've tried setting the proper capabilities to the binary (using `setcap`) but it generates other problems: it can't find some libraries, and when I manually link them in the system paths, a very weird error arises, something about a trap, and it suddenly stops.

If I try to execute the binary using sudo, it does nothing, just exists.

**Comment by oscaracena** [comment]
As a workaround, I've done the following steps:

1. Rename the installation folder to remove the space in the name, and create a symlink to the old name (to not break anything):
```
cd /opt
sudo mv "Beam Studio" BeamStudio
sudo ln -s BeamStudio "Beam Studio"
```

2. Set the needed capabilities to the binary `beam-studio`:

```
cd /opt/BeamStudio
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip beam-studio 
```

3. Link the library `libffmpeg.so` to a system wide path (you could also put the path `/opt/BeamStudio` inside the file `/etc/ld.so.config` and then `sudo ldconfig` to update the lib paths):

```
cd /opt/BeamStudio
ln -s $(pwd)/libffmpeg.so /usr/lib
```

With these steps, beam-studio worked ok.

**Comment by dkdkwizard** [comment]
Hi oscaracena,
Thank you for reporting this issue and a workround.
Because Beam Studio as an electron based app, so if you want to run it as sudo you can also use:
`sudo beam-studio --no-sandbox`.
