### ISSUE TITLE
no library called "libcairo-2" was found

### ISSUE THREAD

**Issue by oscaracena** [flux3dp/beam-studio#14]
When a I launch `beam-studio` in Ubuntu, importing SVG files does not work, and in the console appears the following error:

```
[2020-09-22 11:12:45,ERROR,HTTP] no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': /opt/Beam Studio/resources/backend/flux_api/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
cannot load library 'libcairo.so': /opt/Beam Studio/resources/backend/flux_api/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
``` 

It seems that the application uses a system library (`libpng16.so.16`) which in turns uses another library (`libz.so.1`), and in this case is taken from the provided libs by the app, and has some version collision. 

If I remove that provided library (`sudo rm "/opt/Beam Studio/resources/backend/flux_api/libz.so.1"`), then that problem is fixed, but another one arises. This time is a collision with a TrueType library: `'libcairo.so.2': /lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates`. Again, removing the file `/opt/Beam Studio/resources/backend/flux_api/libfreetype.so.6` fixes the problem.

**Comment by monotonee** [comment]
@oscaracena Again, you crushed it. I was encountering 800-series timeout errors with camera preview and calibration in Beam Studio. Sadly, I'm not well-versed in C, so I began searching for a solution after observing the libcairo errors in stdout. Your expertise saved me a ton of work — thank you.

**Comment by dkdkwizard** [comment]
Hi oscaracena,
We have removed `libz.so.1` and `libfreetype.so.6` in flux_api directory since 1.6.1 stable and 1.7.0 beta.
So this issue should be fixed, please check if this error still occurs, thanks.
