### ISSUE TITLE
Export SVG does not export scale correctly

### ISSUE THREAD

**Issue by ghost** [flux3dp/beam-studio#16]
Exporting an SVG from Beam Studio does not preserve the dimensions correctly. It appears to convert 1mm into 1px upon export, and does not have the DPI set correctly. 

To recreate the problem create any shape in Beam Studio and note the dimensions. Export it to SVG and then import that SVG. The imported shape will be significantly larger than the original shape.

**Comment by dkdkwizard** [comment]
Hi ghost,
We haved fixed SVG scale issue in Beam Studio 1.7.1 beta.
Please check if this issue still happens in 1.7.1 beta.
Thank you.
