### ISSUE TITLE
Ctrl + Z fails with a selected item

### ISSUE THREAD

**Issue by abavery** [flux3dp/beam-studio#3]
Steps to reproduce:

1. Create an object on the grid
2. Select the object
3. Turn on infill
4. Press Ctrl + Z

The infill does not revert as it should

**Comment by dkdkwizard** [comment]
Hi abavery,
    We have fixed windows undo shortcut related bug in Beam Studio 1.2.2-beta, which can be downloaded from our website: https://flux3dp.com/downloads/ .
   Please download the new version of Beam Studio and check if this still happens.
    Thanks.
