### ISSUE TITLE
DXF file cutting order is wrong

### ISSUE THREAD

**Issue by frank26080115** [flux3dp/beam-studio#7]
Beam Studio v1.3.4-beta Windows x64

The following DXF file is a circle with some more slots cut into it. The slots must be cut first, then the circle, otherwise, the whole piece could shift inside the machine and the slots will be cut inaccurately.

Beam Studio generates instructions to cut the circle first. This is wrong!

Cutting inside first and then outside seems to work for SVGs but not DXFs, please fix this.

I have attached the sample file (DXF file inside the ZIP)
[67mm Bahtinov Mask.zip](https://github.com/flux3dp/beam-studio/files/4937056/67mm.Bahtinov.Mask.zip)

**Comment by dkdkwizard** [comment]
Hi @frank26080115 ,

Thank you for reporting this bug.
Beam Studio should cut elements enclosed by other elements first, but it seemed that the enclosed elements was not detected correctly for some DXF files.

We have fixed some enclosing detection for DXF files, and this DXF is cut in correct order in Beam Studio 1.4.0 beta.
Kindly update Beam Studio 1.4.0 beta and this bug should be fixed.
